# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LegalMy.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(43, 30, 341, 271))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 410, 381, 171))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Page = QtWidgets.QMenu(self.menubar)
        self.menu_Page.setObjectName("menu_Page")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionZoom_In_25 = QtWidgets.QAction(MainWindow)
        self.actionZoom_In_25.setObjectName("actionZoom_In_25")
        self.actionZoom_Out_25 = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out_25.setObjectName("actionZoom_Out_25")
        self.actionNormal_Size = QtWidgets.QAction(MainWindow)
        self.actionNormal_Size.setObjectName("actionNormal_Size")
        self.actionFit_To_Window = QtWidgets.QAction(MainWindow)
        self.actionFit_To_Window.setObjectName("actionFit_To_Window")
        self.actionNext_Page = QtWidgets.QAction(MainWindow)
        self.actionNext_Page.setObjectName("actionNext_Page")
        self.actionPrev_Page = QtWidgets.QAction(MainWindow)
        self.actionPrev_Page.setObjectName("actionPrev_Page")
        self.actionNext_File = QtWidgets.QAction(MainWindow)
        self.actionNext_File.setObjectName("actionNext_File")
        self.actionPrev_File = QtWidgets.QAction(MainWindow)
        self.actionPrev_File.setObjectName("actionPrev_File")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionPrint)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_View.addAction(self.actionZoom_In_25)
        self.menu_View.addAction(self.actionZoom_Out_25)
        self.menu_View.addAction(self.actionNormal_Size)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionFit_To_Window)
        self.menu_Page.addAction(self.actionNext_Page)
        self.menu_Page.addAction(self.actionPrev_Page)
        self.menu_Page.addSeparator()
        self.menu_Page.addAction(self.actionNext_File)
        self.menu_Page.addAction(self.actionPrev_File)
        self.menu_Help.addAction(self.actionAbout)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Page.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionOpen.triggered.connect(lambda: self.clicked("Open Was Clicked"))
        self.actionPrint.triggered.connect(lambda: self.clicked("Print Was Clicked"))
        self.actionExit.triggered.connect(lambda: self.clicked("Exit Was Clicked"))
        self.actionZoom_In_25.triggered.connect(lambda: self.clicked("Zoom_In_25. Was Clicked"))
        self.actionZoom_Out_25.triggered.connect(lambda: self.clicked("Zoom_Out_25 Was Clicked"))
        self.actionFit_To_Window.triggered.connect(lambda: self.clicked("Fit_To_Win Was Clicked"))




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.menu_Page.setTitle(_translate("MainWindow", "&Page"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Opening a new file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionPrint.setText(_translate("MainWindow", "Print..."))
        self.actionPrint.setStatusTip(_translate("MainWindow", "Printing the file . . ."))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exiting the file"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionZoom_In_25.setText(_translate("MainWindow", "Zoom In(25%)"))
        self.actionZoom_In_25.setStatusTip(_translate("MainWindow", "Zooming In . . ."))
        self.actionZoom_In_25.setShortcut(_translate("MainWindow", "Ctrl++"))
        self.actionZoom_Out_25.setText(_translate("MainWindow", "Zoom Out(25%)"))
        self.actionZoom_Out_25.setStatusTip(_translate("MainWindow", "Zooming Out . . . "))
        self.actionZoom_Out_25.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionNormal_Size.setText(_translate("MainWindow", "Normal Size"))
        self.actionNormal_Size.setStatusTip(_translate("MainWindow", "Normal Size"))
        self.actionNormal_Size.setShortcut(_translate("MainWindow", "Ctrl+*"))
        self.actionFit_To_Window.setText(_translate("MainWindow", "Fit To Window"))
        self.actionFit_To_Window.setStatusTip(_translate("MainWindow", "Fitting to Window"))
        self.actionFit_To_Window.setShortcut(_translate("MainWindow", "Ctrl+Home"))
        self.actionNext_Page.setText(_translate("MainWindow", "Next Page"))
        self.actionNext_Page.setStatusTip(_translate("MainWindow", "Next Page"))
        self.actionNext_Page.setShortcut(_translate("MainWindow", "Right"))
        self.actionPrev_Page.setText(_translate("MainWindow", "Prev Page"))
        self.actionPrev_Page.setStatusTip(_translate("MainWindow", "Prev Page"))
        self.actionPrev_Page.setShortcut(_translate("MainWindow", "Right"))
        self.actionNext_File.setText(_translate("MainWindow", "Next File"))
        self.actionNext_File.setStatusTip(_translate("MainWindow", "Next File"))
        self.actionNext_File.setShortcut(_translate("MainWindow", "PgUp"))
        self.actionPrev_File.setText(_translate("MainWindow", "Prev File"))
        self.actionPrev_File.setStatusTip(_translate("MainWindow", "Prev File"))
        self.actionPrev_File.setShortcut(_translate("MainWindow", "PgDown"))
        self.actionAbout.setText(_translate("MainWindow", "About "))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionAbout_Qt.setStatusTip(_translate("MainWindow", "About Qt"))
        self.actionAbout_Qt.setShortcut(_translate("MainWindow", "Ctrl+Q"))

    def clicked(self, text):
        self.label_2.setText(text)
        self.label_2.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

